# Shell variables
# Generated by pywal
set wallpaper "{wallpaper}"

# Special
set background '{background}'
set foreground '{foreground}'
set cursor '{cursor}'

# Colors
set color0 '{color0}'
set color1 '{color1}'
set color2 '{color2}'
set color3 '{color3}'
set color4 '{color4}'
set color5 '{color5}'
set color6 '{color6}'
set color7 '{color7}'
set color8 '{color8}'
set color9 '{color9}'
set color10 '{color10}'
set color11 '{color11}'
set color12 '{color12}'
set color13 '{color13}'
set color14 '{color14}'
set color15 '{color15}'

# FZF colors
set -x FZF_DEFAULT_OPTS "
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
set -x LS_COLORS "$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
